### ISSUE TITLE
A few well known "problematic" aur packages

### ISSUE THREAD

**Issue by polygamma** [kitsunyan/pakku#1]
Hey!

Welcome to the *AUR helper business*! :)
Here are a few well known packages, which may be used to validate the function of your helper, which are known to cause problems. Regarding the first two packages: opinions about whether an aur helper should be capable of installing those, or not, differ strongly, so may you decide that for your helper by yourself, but it is nevertheless nice to know about those. 

- `mingw-w64-gcc` - see: https://github.com/polygamma/aurman/issues/17 problem and solution are being discussed over there
- `ros-indigo-desktop-full` - see: https://github.com/actionless/pikaur/issues/53 or [description of aurman dep solving](https://github.com/polygamma/aurman/wiki/Description-of-the-aurman-dependency-solving) which describes a way of fetching needed information about aur packages, so that enough information becomes available and hence allows installing of that package
- `ros-lunar-desktop` - long dep chain, but all in all it is possible to install
- `clion`, `clion-lldb` etc. to check split package support - notice: `clion-lldb` requires also `ncurses5-compat-libs`, the other parts of that split package do not
- `plasma-git-meta` - not possible to install, but it is nice to test the output of your helper to describe the problems which occurred. currently your helper points out the following 2 problems:
  - `discover-git` not fulfillable
  - `oxygen-git` not fulfillable

that is correct, but there is one more unsolvable problem: `botan-1.10` which is a dep of `qca-qt5-git`
way: `plasma-git-meta` to `plasma-nm-git` to `qca-qt5-git`

it would be nice to also display that problem

**Comment by kitsunyan** [comment]
That's serious business, I guess!

Thanks for the list, I'll try to check them all and report here. I already tried to install `ros-lunar-desktop` since it was referenced in AUR Helpers Arch wiki page, but I couldn't install it, several dependencies were invalid. I tried to fix them (commented code lines, etc), but, ultimately, I surrendered: the error was too incomprehensible for me >.<

**Comment by kitsunyan** [comment]
Checked `mingw-w64-gcc`. My resolver doesn't even tries to lookup for `mingw-w64-gcc-base` since it's already provided by `mingw-w64-gcc-base`. Fixed in https://github.com/kitsunyan/pakku/commit/9a2357c70b7a704877515c0a4418a85a5ccecfcd.

**Comment by kitsunyan** [comment]
Checked both `ros-indigo-desktop-full` and `plasma-git-meta`. Now I don't interupt resolving when I found unsatisfied dependency so I could find `python2-catkin-pkg` which is referenced as `python2-catkin_pkg` by another package. This also fixes a problem with incomplete list of missing dependencies. Although, these issues aren't bound. Fixed in https://github.com/kitsunyan/pakku/commit/7306b66419c8e3f1785f2bb22d6851c827f7b671.

**Comment by polygamma** [comment]
FYI: I have just tried to install `ros-lunar-desktop` again to see, if it is still possible to install, and it is.
I used my aur helper (obviously) with:
`aurman -S ros-lunar-desktop --pgp_fetch --noedit --noconfirm` in a virtual machine with just `base`, `base-devel` and `aurman` installed.

You may use `aurman -S ros-lunar-desktop --solution_way` to see in which order `aurman` is going to install packages, without the need to install anything, to compare it with what your aur helper calculates. Alternatively, if you want even more information: https://github.com/polygamma/aurman/wiki/Using-aurman-as-dependency-solver

**Comment by kitsunyan** [comment]
For instance, I can't build `ros-lunar-turtlesim`. Neither with pakku nor with aurman.

```
[ 96%] Generating include/turtlesim/moc_turtle_frame.cpp
standard input:0: Note: No relevant classes found. No output generated.
[ 98%] Building CXX object CMakeFiles/turtlesim_node.dir/include/turtlesim/moc_turtle_frame.cpp.o
c++: error: /home/aur/.cache/aurman/ros-lunar-turtlesim/src/build/include/turtlesim/moc_turtle_frame.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [CMakeFiles/turtlesim_node.dir/build.make:139: CMakeFiles/turtlesim_node.dir/include/turtlesim/moc_turtle_frame.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 98%] Built target mimic
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/turtlesim_node.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by polygamma** [comment]
Do you have cmake-git instead of cmake or qt5-base-git instead of qt5-base installed? Those tend to make problems, even though they shouldn't...

**Comment by polygamma** [comment]
Addition: You could also try running aurman with `--deep_search` to see what makes the difference.

**Comment by kitsunyan** [comment]
Nah, forget about it. qt5 uses new `statx` syscall which is not whitelisted in docker (I test all these builds in docker container).

**Comment by kitsunyan** [comment]
Finally, I successfully built `ros-lunar-desktop`. I wanted to checkout the commit in which `.SRCINFO` was changed (actually, I used git bisect to find a suitable commit), but it seems to be harmful. Packagers often forget to update `.SRCINFO` or `pkgrel` making changes to `PKGBUILD`, so I decided to put it off.

I tested `clion`, it seems that everything works as you describe.

**Comment by kitsunyan** [comment]
So, thanks again for the list, I appreciate it. It was really helpful for me to understand some rare cases.

**Comment by polygamma** [comment]
You are very welcome :)
