### ISSUE TITLE
Failed to compile for aarch64 (raspberry pi 3b)

### ISSUE THREAD

**Issue by ava1ar** [kitsunyan/pakku#12]
Trying to build latest stable version, getting following error:

> 
GEN: completion/bash
GEN: completion/zsh
NIM: lib/bisect
CC: bisect
CC: stdlib_system
CC: stdlib_future
CC: stdlib_os
CC: stdlib_osproc
CC: stdlib_re
CC: stdlib_strutils
CC: stdlib_macros
CC: stdlib_parseutils
CC: stdlib_math
CC: stdlib_algorithm
CC: stdlib_times
CC: stdlib_posix
CC: stdlib_ospaths
CC: stdlib_strtabs
CC: stdlib_hashes
CC: stdlib_streams
CC: stdlib_cpuinfo
CC: stdlib_linux
CC: stdlib_pcre
CC: stdlib_rtarrays
NIM: lib/install
CC: install
CC: stdlib_system
CC: stdlib_future
CC: stdlib_os
CC: stdlib_posix
CC: stdlib_sequtils
CC: stdlib_strutils
CC: stdlib_macros
CC: stdlib_parseutils
CC: stdlib_math
CC: stdlib_algorithm
CC: stdlib_times
CC: stdlib_ospaths
NIM: src/pakku
utils.nim(130, 24) Error: cannot evaluate at compile time: SIGINT
make: *** [Makefile:130: src/pakku] Error 1

**Comment by kitsunyan** [comment]
Yes, I know about that. Actually it's not the only error. If I explicitly declare SIGINT, there will be a lot of other places where compiler will fail. It more seems like nim bug for me, I'm not sure I'll be able to deal with all these errors without reinventing the stuff that I shouldn't reinvent.

**Comment by ava1ar** [comment]
Got it, thanks.

**Comment by kitsunyan** [comment]
This time is was easy to fix it, at least I was able to compile pakku in chroot after this commit https://github.com/kitsunyan/pakku/commit/07d3d493093f2222801ff9c71e27198575f90240.

Arch Linux ARM has its own repository named "aur" which conflicts with pakku. You should be able to rename pakku's fake repository using `AurRepo` config option https://github.com/kitsunyan/pakku/commit/56e82963b465116af32231aa531e8f6344826eab.

There are a lot of PKGBUILDs in AUR which don't have a complete list of supported architectures. `makepkg` is able to ignore it using `--ignorearch` option. You can disable architecture checking in pakku configuration https://github.com/kitsunyan/pakku/commit/7accdb6dab38f0ecb49669b7ddc04dc4f5facd14.

**Comment by ava1ar** [comment]
Thanks a lot for quick fix! Will check it out today.

**Comment by kitsunyan** [comment]
My friend reported that she was able to build the program under armv7h. I think building should work fine now.
