### ISSUE TITLE
Remove unused pakku cache repository git folders with -Sc

### ISSUE THREAD

**Issue by bernimoses** [kitsunyan/pakku#14]
It would be nice if the repositories in `~/.cache/pakku/repositories/` would be removed with `pakku -Sc` if the package is not installed anymore.

Thanks. 😊

**Comment by kitsunyan** [comment]
Done! https://github.com/kitsunyan/pakku/commit/f227d1088f6a8aee3654804b5fd0110e15532c5b

**Comment by bernimoses** [comment]
Nice, thanks! Keep up the amazing work. 👍
