### ISSUE TITLE
split packages

### ISSUE THREAD

**Issue by polygamma** [kitsunyan/pakku#2]
pakku is currently not able to install `clion-lldb`. see:

```
[jonny@jonny-arch-pc ~]$ pakku -S clion-lldb
:: Checking AUR database...
downloading full package descriptions...
resolving dependencies...
error: unable to satisfy dependency '' required by clion-lldb
```

**Comment by kitsunyan** [comment]
That's because srcinfo contains empty dependency reference. I'm not sure this is correct syntax, but for fault tolerance sake I should just ignore them. My srcinfo parser isn't perfect.

Fixed it in https://github.com/kitsunyan/pakku/commit/3b984b6b8f6107ec37c35cf4091e1a85a0a22abb

**Comment by polygamma** [comment]
Have you heard of [this](https://wiki.archlinux.org/index.php/AurJson) ? Parsing srcinfo is something one should not do

**Comment by kitsunyan** [comment]
AurJson doesn't provide package groups. I also don't know how it represents arch-specific dependencies (e.g. `depends_x86_64`).

For repo packages I use libalpm directly.

**Comment by polygamma** [comment]
AurJson does provide package groups for sure, where does it not provide a group, but should?

**Comment by kitsunyan** [comment]
My bad, it really provides groups. But it doesn't provide arch-specific dependencies.

`https://aur.archlinux.org/rpc.php?v=5&type=info&arg[]=lmms-git`

```
{
  "version": 5,
  "type": "multiinfo",
  "resultcount": 1,
  "results": [
    {
      "ID": 464384,
      "Name": "lmms-git",
      "PackageBaseID": 25699,
      "PackageBase": "lmms-git",
      "Version": "1.2.0.rc4.r49.g46ef3c6a1-2",
      "Description": "The Linux MultiMedia Studio.",
      "URL": "http: \/\/lmms.sourceforge.net\/",
      "NumVotes": 26,
      "Popularity": 0.578338,
      "OutOfDate": null,
      "Maintainer": "difarem",
      "FirstSubmitted": 1240168468,
      "LastModified": 1511626448,
      "URLPath": "\/cgit\/aur.git\/snapshot\/lmms-git.tar.gz",
      "Depends": [
        "sdl",
        "glib2",
        "fluidsynth",
        "libpng",
        "libvorbis",
        "libxft",
        "libxinerama",
        "qt4",
        "sdl_sound",
        "libsamplerate",
        "shared-mime-info",
        "fltk"
      ],
      "MakeDepends": [
        "git",
        "cmake",
        "ladspa",
        "libxft",
        "freetype2",
        "fftw",
        "stk",
        "wine",
        "gcc-multilib"
      ],
      "OptDepends": [
        "wine",
        "fftw",
        "stk",
        "pulseaudio"
      ],
      "Conflicts": [
        "lmms",
        "lmms-extras"
      ],
      "Provides": [
        "lmms",
        "lmms-extras"
      ],
      "License": ["GPL"],
      "Keywords": []
    }
  ]
}
```

**Comment by polygamma** [comment]
You are right about those deps, one definitely has to parse the .SRCINFO or PKGBUILD to get those things right, but I personally, do not touch those arch specific things, since they are so rare and destroy all of the performance, since one needs to parse those files... I guess it would be best to create a patch for AurJson to properly include those things?

**Comment by kitsunyan** [comment]
Of course it would be nice to have this feature in AurJson. But I think that performance is not so important unless you're trying to install something like `ros-lunar-desktop`.
