### ISSUE TITLE
Disable PKBUILD editing dialog

### ISSUE THREAD

**Issue by YanDoroshenko** [kitsunyan/pakku#21]
Is there a possibility to permanently disable a View and edit XXX/PKGBUILD? [Y/n/s/a/?] dialog?

**Comment by kitsunyan** [comment]
No, but you can enable `ViewNoDefault` option so default answer would be "No".

**Comment by YanDoroshenko** [comment]
@kitsunyan  Well that sucks. Any chance it will be implemented?

**Comment by YanDoroshenko** [comment]
@polygamma I come from yaourt and it was implemented there so I think I just got used to it. I never edit PKGBUILDs so for me it's just a stupid question I always answer the same.

**Comment by kitsunyan** [comment]
@YanDoroshenko This feature allows you to _inspect_ PKGBUILD so you could make sure it's safe. Editing is just a pleasant addition. Disregarding the content of PKGBUILDs is a bad habit, and yaourt indulges it making such config options. I don't want to repeat its mistakes.

**Comment by YanDoroshenko** [comment]
@kitsunyan OK, that makes sense, thanks for the explanation. Closing the issue.
