### ISSUE TITLE
Out of Date plus colors

### ISSUE THREAD

**Issue by seafox** [kitsunyan/pakku#25]
I think your helper has the potential to become the best out here in terms of performance and compatibility with pacman as Nim can easily align to or even adapt C routines if required. Sure some extra features like `trizen -C` to read AUR comments would be a welcome extra.

The most essential omission currently is absence of Out of Date line in package info, preferably with color, according to pacman.conf (most compatible, as pacaur) or separate settings (in pakku.conf).
IMO the best out-of-date implementation as the reference (with Color and VerbosePkgLists enabled) has pacaur, for instance see currently outdated `pacaur -Si visual-studio-code-insiders`

**Comment by kitsunyan** [comment]
I don't like the idea of using additional colors in this output. However, displaying out-of-date flag might be useful. Added in https://github.com/kitsunyan/pakku/commit/c0dd5e7dedf996c78617e21a7ea6bd2e3553dbfb.

**Comment by seafox** [comment]
> I don't like the idea of using additional colors in this output.

As some folks might like it (especially in cases like out-of-date flag), perhaps you could consider including Color support as an option later, just like it's available in other helpers. Thanks again for adding the missed field!
