### ISSUE TITLE
Basic UI

### ISSUE THREAD

**Issue by mrvik** [kitsunyan/pakku#26]
Hi! A lot of thanks for this good job. I've written a (very basic) GTK frontend. It's available as [pakku-gui](https://gitlab.com/mrvik/pakku-gui) on GitLab and now on the AUR. I thought you may like to know it.
Thanks again for keeping this fabolous software.

**Comment by kitsunyan** [comment]
Hi! Sorry, I don't have much time for pakku right now, so it took this long for my reply. I'm not sure that GUI is necessary for package manager (or its wrapper). Besides, your tool only starts a new terminal window executing `pakku` with some arguments. This seems very inflexible.

When I choose install/remove/sysupgrade in your tool, I can't see any warnings and errors after completing the process. The terminal window closes unconditionally, so I can't learn that package wasn't found or I can miss important warning messages during upgrade.

Also, pakku supports more features than just installing and removing packages. `-Sn`, `-Sz`, `-Sc`, `-Qdttt`… With your set of features this could be `$aurhelpername-gui`, not just pakku. Anyway, that's good if you find your tool useful to you, and somebody may find it useful too.

**Comment by mrvik** [comment]
Thanks for the feedback, I'll try to improve it. Closing this issue not-issue.
