### ISSUE TITLE
Issues with SUDO_UID

### ISSUE THREAD

**Issue by Ape** [kitsunyan/pakku#29]
It seems that pakku is using `SUDO_UID` to determine the user. However this fails in a scenario where I am using sudo to change to a non-root user outside pakku. Consider the following case:

```
user1@localhost$ sudo -iu user2
user2@localhost$ pakku -S pakku
```

It seems that pakku tries to access `~user1` with user2. I would expect it to use `~user2` instead. The fact that I was user1 earlier should not affect the programs I run in the shell of user2 in any way.

**Comment by kitsunyan** [comment]
> The fact that I was user1 earlier should not affect the programs I run in the shell of user2 in any way.

Checking for `SUDO_UID` allows to use `sudo pakku -S …` (`SudoExec` config option is implemented the same way) or even `sudo -s` and then `pakku -S aurpackage`, so I can't agree with this statement: in this particular case user2 is root.

Do you have any suggestions how I can improve this?

**Comment by kitsunyan** [comment]
It was the first idea crossed my mind, but I'm not sure if it will suit @Ape.

**Comment by Ape** [comment]
Yes, it would fix my use case if this switch back was only done for root.

**Comment by kitsunyan** [comment]
pakku is designed so it can work from root. Moreover, using `sudo pakku -S` you can enter a password only once which can be useful when you build and install multiple packages. Pakku drops its priveleges when it writes to the disk or uses makepkg.

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/pakku/commit/e6b77b3fbd3b3c526180dfea1eb8a34de63efb95
