### ISSUE TITLE
conflict detection

### ISSUE THREAD

**Issue by polygamma** [kitsunyan/pakku#3]
e.g. `pakku -S cower-git cower` does not warn about trying to install conflicting packages.

You just reach a point during installation like:
`warning: removing 'cower' from target list because it conflicts with 'cower-git'`
pakku should not even try to install those packages imho.

**Comment by kitsunyan** [comment]
In these cases pacman warns about conflict but continues installing the last package. I think I should do something like that too.

**Comment by polygamma** [comment]
I see your point, but I think not everything `pacman` does is the way to go. That is an example for it ;)
Sure, in general one should adapt `pacman` behavior, so that no unwanted side effects occur, but I think this is an exception. If I type in `pacman -S package1 package2` that means that I want to install `package1` and `package2`. If that is not possible, there should be at least a clear warning about that in the beginning.
Just seeing `warning: removing 'package1' from target list because it conflicts with 'package2'` somewhere during the build process is not very user friendly, I guess

**Comment by kitsunyan** [comment]
I'm going to make this warning at the beginning of build process, before user confirms "Proceed the building?". So it will be clear and it will look like pacman!

**Comment by kitsunyan** [comment]
Fixed in https://github.com/kitsunyan/pakku/commit/75b2f60bf15a9d49859b262a47da30ec70614a5e
