### ISSUE TITLE
Error message and lots of warnings

### ISSUE THREAD

**Issue by stefanhusmann** [kitsunyan/pakku#30]
Not sure why (is used to work, and pakku's code did not change) but for a week or so runnig pakku -Suy now results in an error message and lots of warnings.

Error: failed to parse server response

Warnings: ... was not found in AUR.

The ... stands for many packages that actually _are_ in AUR but also in my personal repo. Is this only on my side?

**Comment by stefanhusmann** [comment]
Here the output: 

[pakkuout.txt](https://github.com/kitsunyan/pakku/files/2386741/pakkuout.txt)

**Comment by kitsunyan** [comment]
Can you try this? https://github.com/kitsunyan/pakku/commit/68854ac3f09df6e7ad496f446500ad8df9249330

**Comment by stefanhusmann** [comment]
Works fine. Thanks.
