### ISSUE TITLE
strip binary

### ISSUE THREAD

**Issue by juancarlospaco** [kitsunyan/pakku#33]
Make install should strip binary:

```
$ du -h /usr/local/bin/pakku
860K    /usr/local/bin/pakku

$ sudo strip --strip-all /usr/local/bin/pakku

$ du -h /usr/local/bin/pakku
630K    /usr/local/bin/pakku
```

Same with other binaries if any.

**Comment by kitsunyan** [comment]
`makepkg` will strip binary if `strip` option is specified in `OPTIONS` in `makepkg.conf` (which is default).

**Comment by juancarlospaco** [comment]
[this file](https://github.com/kitsunyan/pakku/blob/master/Makefile)

**Comment by juancarlospaco** [comment]
Ok, then closing the issue.
