### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by juancarlospaco** [kitsunyan/pakku#34]
Document Install Instructions on the README.

**Comment by kitsunyan** [comment]
It's available in AUR. Maybe I should mention it in README, but Arch Linux users should know how to use AUR if they want use AUR helper.

**Comment by juancarlospaco** [comment]
Maybe you should mention it in README.

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/pakku/commit/fbb01f7d7c5d3b9830b2cb30b60302711f9e278e
