### ISSUE TITLE
Upload to Nimble

### ISSUE THREAD

**Issue by juancarlospaco** [kitsunyan/pakku#35]
- Upload to Nimble.
- Document on the README that you can install using `nimble install pakku`

**Comment by kitsunyan** [comment]
Why Nimble? Pakku is Arch Linux-specific program, moreover, it's AUR helper, so it should be installed from AUR.

**Comment by juancarlospaco** [comment]
Why not both. :cat:

**Comment by juancarlospaco** [comment]
Ok, then closing the issue.
