### ISSUE TITLE
Question on exporting variables

### ISSUE THREAD

**Issue by AladW** [kitsunyan/pakku#4]
With https://github.com/kitsunyan/pakku/commit/864cc0373fd6095295f68cc44d1657bd17269732, does `pakku` still need a Red entry in the [wiki table](https://wiki.archlinux.org/index.php/AUR_helpers#Active) for "Clean build"?

**Comment by kitsunyan** [comment]
No. As you can see, it still exports `MAKEPKG_CONF` variable (actually, the value is empty, and this variable is barely harmful).

I removed all setenvs in https://github.com/kitsunyan/pakku/commit/8d0508a73cd984fa532ff9f29cbedba5d0e0aa81 which is included to v0.3, so no, it doesn't need red entry anymore.
