### ISSUE TITLE
Feature Request: customizepkg

### ISSUE THREAD

**Issue by stefanhusmann** [kitsunyan/pakku#5]
What about supporting customizepkg?

It is a nice tool to let you automtize changing PKGBUILDs on the fly. It is usefull for some circumstance, e.g. if you want another download mirror as the AUR default provides ore change default configure options.

In fact there are several flavours of customizepkg in the AUR, but they all use the same interface to the user or to aur helpers.

**Comment by kitsunyan** [comment]
I think I can add a pre-build script to configuration options which will be executed after checking `PKGBUILD` and before `makepkg`. User can specify `customizepkg` there or anything he wants. What do you think?

**Comment by stefanhusmann** [comment]
I think that would be even more flexible.

**Comment by kitsunyan** [comment]
Done! https://github.com/kitsunyan/pakku/commit/769413c9f01676658acd33fedd90c038335af835

**Comment by stefanhusmann** [comment]
Thanks, works fine!
