### ISSUE TITLE
pakku: error while loading shared libraries: libalpm.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PMunch** [kitsunyan/pakku#50]
Title says it all really. Checking the pacman package I can see that libalpm has updated to v12:

```
$ pacman -Ql pacman | grep libalpm.so
pacman /usr/lib/libalpm.so
pacman /usr/lib/libalpm.so.12
pacman /usr/lib/libalpm.so.12.0.0
```

**Comment by mrvik** [comment]
A rebuild should work, but rebuilds are blocked until #49 is merged due to changes on pacman bash completion.

**Comment by lots0logs** [comment]
@kitsunyan 

![bump](https://user-images.githubusercontent.com/4675662/69787249-b4344800-1181-11ea-8d8d-64e3c13d502a.gif)

**Comment by kitsunyan** [comment]
Fixed by the patch. New version was released. Sorry for delay.
