### ISSUE TITLE
Build fails with "Error: undeclared identifier: 'SystemError'"

### ISSUE THREAD

**Issue by TwoLeaves** [kitsunyan/pakku#51]
Code no longer builds with Nim 1.0.2, complaining:
"Error: undeclared identifier: 'SystemError'."

According to the changelog (https://github.com/nim-lang/Nim/blob/6e83746caabca00ab2b97a81bd732de4588996fe/changelog.md), SystemError is now CatchableError: "The exception hierarchy was slightly reworked, SystemError was renamed to CatchableError and is the new base class for any exception that is guaranteed to be catchable. This change should have minimal impact on most existing Nim code."

**Comment by kitsunyan** [comment]
Pakku should be compatible with Nim 1.0 right now. Alas, they deprecated their list comprehensions, so there are a lot of warnings during compilation, but I can't do anything with it right now.
