### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [kitsunyan/pakku#52]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by mrvik** [comment]
This is on the makepkg side, not on the aur wrapper one so pakku can't help improve this.
But you're right, the compression choice helps to reduce the build time. Consider also the newly supported zstd.

**Comment by es20490446e** [comment]
I just read that Arch is planning to default to zstd, so no fix will be needed here.

- [Arch thread](https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029520.html)
- [Pacman git log](https://git.archlinux.org/svntogit/packages.git/log/?h=packages/pacman)
