### ISSUE TITLE
Feature Request: Use $EDITOR variable instead of asking every time

### ISSUE THREAD

**Issue by 1024x2** [kitsunyan/pakku#7]
Currently, pakku asks for an editor every time you want to edit a file. This can get a bit tedious when you're installing multiple packages. I'd like it if pakku checked the $EDITOR enviroment variable before asking for an editor.

**Comment by kitsunyan** [comment]
It checks for `EDITOR` and `VISUAL` variables so it shouldn't ask if variable is set https://github.com/kitsunyan/pakku/blob/5f7f4f2d713025f05cbc240323b6fe47bb6dbe24/src/feature/syncinstall.nim#L287

Do you have `SudoExec` enabled in config file?

**Comment by 1024x2** [comment]
Ah, my bad! Sudo wasn't preserving the $EDITOR variable. Closing now.

**Comment by kitsunyan** [comment]
So you used `sudo pakku -S …` or you have `SudoExec` enabled? Actually I though about using `sudo -E` instead of just `sudo` if `SudoExec` enabled, but I wanted to discuss security implications of that choice somewhere.
